export const getSearchData = () => {
  return [
    {
      id: "01",
      title: "Loan Dispute",
      content:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
      category: "Loan",
      decision: "Upheld",
      company: "Barclays Bank Plc",
      date: "2022-11-08",
    },
    {
      id: "02",
      title: "Credit Card Fraud",
      content: "Unauthorized transaction on credit card.",
      category: "Credit Card",
      decision: "Rejected",
      company: "HSBC Holdings",
      date: "2023-02-15",
    },
    {
      id: "03",
      title: "Account Closure Issue",
      content: "Customer dissatisfied with account closure process.",
      category: "Current Account",
      decision: "Partially Upheld",
      company: "Lloyds Bank",
      date: "2023-01-05",
    },
    {
      id: "04",
      title: "Insurance Claim",
      content: "Insurance claim dispute regarding coverage.",
      category: "Insurance",
      decision: "Upheld",
      company: "Aviva Plc",
      date: "2023-03-22",
    },
    {
      id: "05",
      title: "Mortgage Payment Issue",
      content: "Incorrect mortgage payment details provided.",
      category: "Mortgage",
      decision: "Rejected",
      company: "Santander UK",
      date: "2023-04-10",
    },
    {
      id: "06",
      title: "Savings Account Interest",
      content: "Interest not applied correctly to savings account.",
      category: "Savings Account",
      decision: "Upheld",
      company: "Nationwide Building Society",
      date: "2022-12-17",
    },
    {
      id: "07",
      title: "PPI Complaint",
      content: "Mis-sold payment protection insurance.",
      category: "PPI",
      decision: "Upheld",
      company: "NatWest Bank",
      date: "2023-01-28",
    },
    {
      id: "08",
      title: "Loan Overpayment",
      content: "Overpayment on loan not refunded.",
      category: "Loan",
      decision: "Rejected",
      company: "Barclays Bank Plc",
      date: "2023-03-01",
    },
    {
      id: "09",
      title: "Bank Fees Dispute",
      content: "Dispute regarding excessive overdraft fees.",
      category: "Overdraft",
      decision: "Upheld",
      company: "Metro Bank",
      date: "2023-05-06",
    },
    {
      id: "10",
      title: "Unauthorised Account Activity",
      content: "Customer noticed unauthorised withdrawals.",
      category: "Current Account",
      decision: "Rejected",
      company: "HSBC Holdings",
      date: "2023-02-20",
    },
    {
      id: "11",
      title: "Missed Direct Debit",
      content: "Bank missed scheduled direct debit payment.",
      category: "Direct Debit",
      decision: "Upheld",
      company: "TSB Bank",
      date: "2023-04-15",
    },
    {
      id: "12",
      title: "Delay in Fund Transfer",
      content: "Delay in transferring funds between accounts.",
      category: "Funds Transfer",
      decision: "Partially Upheld",
      company: "Barclays Bank Plc",
      date: "2023-03-25",
    },
    {
      id: "13",
      title: "Incorrect Credit Report",
      content: "Bank reported incorrect details on credit report.",
      category: "Credit Report",
      decision: "Upheld",
      company: "Experian Plc",
      date: "2023-05-12",
    },
    {
      id: "14",
      title: "Fraudulent Loan Application",
      content: "Fraudulent loan taken out in customer's name.",
      category: "Loan",
      decision: "Rejected",
      company: "Lloyds Bank",
      date: "2023-01-18",
    },
    {
      id: "15",
      title: "Lost Cheque Issue",
      content: "Cheque lost during bank processing.",
      category: "Cheque",
      decision: "Upheld",
      company: "Halifax",
      date: "2022-12-30",
    },
    {
      id: "16",
      title: "Card Decline Error",
      content: "Debit card declined during a transaction.",
      category: "Debit Card",
      decision: "Rejected",
      company: "HSBC Holdings",
      date: "2023-04-22",
    },
    {
      id: "17",
      title: "Foreign Transaction Charges",
      content: "Customer disputes unexpected foreign transaction charges.",
      category: "Credit Card",
      decision: "Partially Upheld",
      company: "Santander UK",
      date: "2023-02-08",
    },
    {
      id: "18",
      title: "Standing Order Cancellation",
      content: "Standing order cancelled without customer consent.",
      category: "Standing Order",
      decision: "Upheld",
      company: "NatWest Bank",
      date: "2023-03-14",
    },
    {
      id: "19",
      title: "Mortgage Interest Rate Dispute",
      content: "Incorrect interest rate applied to mortgage.",
      category: "Mortgage",
      decision: "Rejected",
      company: "Barclays Bank Plc",
      date: "2023-01-11",
    },
    {
      id: "20",
      title: "ATM Withdrawal Error",
      content: "ATM did not dispense cash but account debited.",
      category: "ATM",
      decision: "Upheld",
      company: "Nationwide Building Society",
      date: "2023-05-19",
    },
    {
      id: "21",
      title: "Testing Date Filter",
      content: "ATM did not dispense cash but account debited.",
      category: "ATM",
      decision: "Upheld",
      company: "Nationwide Building Society",
      date: "2024-10-09",
    },
    {
      id: "22",
      title: "Duplicate Transaction",
      content: "Customer charged twice for the same transaction.",
      category: "Debit Card",
      decision: "Rejected",
      company: "Barclays Bank Plc",
      date: "2023-06-12",
    },
    {
      id: "23",
      title: "Misapplied Insurance Premium",
      content: "Insurance premium taken from wrong account.",
      category: "Insurance",
      decision: "Partially Upheld",
      company: "Aviva Plc",
      date: "2023-06-25",
    },
    {
      id: "24",
      title: "Loan Repayment Discrepancy",
      content: "Discrepancy in final loan repayment amount.",
      category: "Loan",
      decision: "Rejected",
      company: "Lloyds Bank",
      date: "2023-07-02",
    },
    {
      id: "25",
      title: "Unclaimed Cashback Offer",
      content: "Bank did not apply cashback offer to account.",
      category: "Credit Card",
      decision: "Upheld",
      company: "HSBC Holdings",
      date: "2023-07-15",
    },
    {
      id: "26",
      title: "Savings Account Closure Error",
      content: "Savings account closed without proper notice.",
      category: "Savings Account",
      decision: "Upheld",
      company: "Nationwide Building Society",
      date: "2023-08-05",
    },
    {
      id: "27",
      title: "Delayed Mortgage Approval",
      content: "Unnecessary delay in mortgage approval process.",
      category: "Mortgage",
      decision: "Rejected",
      company: "Santander UK",
      date: "2023-08-19",
    },
    {
      id: "28",
      title: "Incorrect Standing Order Amount",
      content: "Standing order executed with incorrect amount.",
      category: "Standing Order",
      decision: "Partially Upheld",
      company: "NatWest Bank",
      date: "2023-09-01",
    },
    {
      id: "29",
      title: "Credit Limit Reduction",
      content: "Customer disputes a sudden reduction in credit limit.",
      category: "Credit Card",
      decision: "Upheld",
      company: "Barclays Bank Plc",
      date: "2023-09-10",
    },
    {
      id: "30",
      title: "Lost ATM Card",
      content: "Bank failed to block the card after it was reported lost.",
      category: "ATM",
      decision: "Upheld",
      company: "Nationwide Building Society",
      date: "2023-09-22",
    },
    {
      id: "31",
      title: "Unapproved Direct Debit",
      content: "Direct debit processed without authorization.",
      category: "Direct Debit",
      decision: "Rejected",
      company: "TSB Bank",
      date: "2023-09-28",
    },
    {
      id: "32",
      title: "Incorrect Interest Rate",
      content: "Savings account offered incorrect interest rate.",
      category: "Savings Account",
      decision: "Partially Upheld",
      company: "HSBC Holdings",
      date: "2023-10-03",
    },
    {
      id: "33",
      title: "Credit Card Limit Dispute",
      content: "Credit card limit was decreased without notice.",
      category: "Credit Card",
      decision: "Rejected",
      company: "Lloyds Bank",
      date: "2023-10-05",
    },
    {
      id: "34",
      title: "Insurance Overcharge",
      content: "Customer was charged double for an insurance premium.",
      category: "Insurance",
      decision: "Upheld",
      company: "Aviva Plc",
      date: "2023-10-07",
    },
    {
      id: "35",
      title: "Misprocessed Cheque",
      content: "Cheque was processed twice, causing overdraft fees.",
      category: "Cheque",
      decision: "Partially Upheld",
      company: "Barclays Bank Plc",
      date: "2023-10-09",
    },
    {
      id: "36",
      title: "Bank Account Frozen",
      content: "Bank account was frozen due to suspected fraud.",
      category: "Current Account",
      decision: "Rejected",
      company: "HSBC Holdings",
      date: "2023-10-15",
    },
    {
      id: "37",
      title: "PPI Refund Issue",
      content: "PPI refund was processed incorrectly.",
      category: "PPI",
      decision: "Upheld",
      company: "NatWest Bank",
      date: "2023-10-18",
    },
    {
      id: "38",
      title: "Delayed Loan Disbursement",
      content: "Loan disbursement was delayed beyond the promised date.",
      category: "Loan",
      decision: "Rejected",
      company: "Lloyds Bank",
      date: "2023-10-22",
    },
    {
      id: "39",
      title: "Overcharged ATM Fee",
      content: "ATM withdrawal incurred unexpected charges.",
      category: "ATM",
      decision: "Upheld",
      company: "Nationwide Building Society",
      date: "2023-11-01",
    },
    {
      id: "40",
      title: "Fraudulent Transaction",
      content: "Unauthorized transaction on current account.",
      category: "Current Account",
      decision: "Rejected",
      company: "Santander UK",
      date: "2023-11-07",
    },
    {
      id: "41",
      title: "Misplaced Savings Account Funds",
      content: "Funds transferred to wrong account in error.",
      category: "Savings Account",
      decision: "Upheld",
      company: "Nationwide Building Society",
      date: "2023-11-15",
    },
    {
      id: "42",
      title: "Mortgage Overpayment",
      content: "Overpayment on mortgage not refunded.",
      category: "Mortgage",
      decision: "Partially Upheld",
      company: "Lloyds Bank",
      date: "2023-11-20",
    },
    {
      id: "43",
      title: "Foreign Transaction Decline",
      content: "Foreign debit card transaction declined without reason.",
      category: "Debit Card",
      decision: "Rejected",
      company: "Barclays Bank Plc",
      date: "2023-11-25",
    },
    {
      id: "44",
      title: "Standing Order Not Processed",
      content: "Bank failed to process standing order.",
      category: "Standing Order",
      decision: "Upheld",
      company: "NatWest Bank",
      date: "2023-11-30",
    },
    {
      id: "45",
      title: "Incorrect Credit Report Update",
      content: "Incorrect information sent to credit agencies.",
      category: "Credit Report",
      decision: "Rejected",
      company: "Experian Plc",
      date: "2023-12-05",
    },
    {
      id: "46",
      title: "ATM Out of Service",
      content: "ATM out of service when needed most.",
      category: "ATM",
      decision: "Partially Upheld",
      company: "HSBC Holdings",
      date: "2023-12-10",
    },
    {
      id: "47",
      title: "Cheque Returned Unpaid",
      content: "Cheque was returned unpaid without notification.",
      category: "Cheque",
      decision: "Rejected",
      company: "Barclays Bank Plc",
      date: "2023-12-20",
    },
    {
      id: "48",
      title: "Lost Debit Card",
      content: "Bank delayed issuing a replacement debit card.",
      category: "Debit Card",
      decision: "Upheld",
      company: "Lloyds Bank",
      date: "2023-12-24",
    },
    {
      id: "49",
      title: "Mortgage Payment Date Issue",
      content: "Mortgage payment date changed without notice.",
      category: "Mortgage",
      decision: "Partially Upheld",
      company: "Santander UK",
      date: "2023-12-28",
    },
    {
      id: "50",
      title: "Loan Disbursement Issue",
      content: "Loan disbursement was delayed.",
      category: "Loan",
      decision: "Rejected",
      company: "Barclays Bank Plc",
      date: "2023-12-30",
    },
    {
      id: "51",
      title: "Fraudulent Loan Transaction",
      content: "Unauthorized loan taken out in customer’s name.",
      category: "Loan",
      decision: "Rejected",
      company: "HSBC Holdings",
      date: "2024-01-04",
    },
    {
      id: "52",
      title: "Direct Debit Error",
      content: "Direct debit was taken twice for the same payment.",
      category: "Direct Debit",
      decision: "Upheld",
      company: "NatWest Bank",
      date: "2024-01-12",
    },
    {
      id: "53",
      title: "Delayed Insurance Payment",
      content: "Insurance payout was delayed for several weeks.",
      category: "Insurance",
      decision: "Partially Upheld",
      company: "Aviva Plc",
      date: "2024-01-18",
    },
    {
      id: "54",
      title: "Mortgage Interest Overcharge",
      content: "Incorrect mortgage interest rate charged to the account.",
      category: "Mortgage",
      decision: "Rejected",
      company: "Lloyds Bank",
      date: "2024-01-22",
    },
    {
      id: "55",
      title: "ATM Dispense Failure",
      content: "ATM failed to dispense money but debited account.",
      category: "ATM",
      decision: "Upheld",
      company: "Barclays Bank Plc",
      date: "2024-01-30",
    },
    {
      id: "56",
      title: "Unapplied Cashback",
      content: "Cashback offer was not applied to credit card account.",
      category: "Credit Card",
      decision: "Rejected",
      company: "HSBC Holdings",
      date: "2024-02-05",
    },
    {
      id: "57",
      title: "Delayed Standing Order",
      content: "Standing order payment was delayed, causing overdraft fees.",
      category: "Standing Order",
      decision: "Upheld",
      company: "Santander UK",
      date: "2024-02-15",
    },
    {
      id: "58",
      title: "Unrecognized Overdraft Charges",
      content: "Customer disputes unexpected overdraft charges.",
      category: "Overdraft",
      decision: "Partially Upheld",
      company: "Metro Bank",
      date: "2024-02-22",
    },
    {
      id: "59",
      title: "Cheque Processing Error",
      content: "Cheque was lost in processing, causing a delay in payment.",
      category: "Cheque",
      decision: "Upheld",
      company: "Lloyds Bank",
      date: "2024-03-01",
    },
    {
      id: "60",
      title: "Foreign Transaction Decline",
      content: "Foreign card transaction was declined without reason.",
      category: "Debit Card",
      decision: "Rejected",
      company: "Barclays Bank Plc",
      date: "2024-03-08",
    },
    {
      id: "61",
      title: "Delayed Loan Payment",
      content: "Loan payment was delayed and did not reflect in account.",
      category: "Loan",
      decision: "Upheld",
      company: "Santander UK",
      date: "2024-03-15",
    },
    {
      id: "62",
      title: "Savings Account Fee Dispute",
      content: "Unexpected fees applied to savings account.",
      category: "Savings Account",
      decision: "Rejected",
      company: "Nationwide Building Society",
      date: "2024-03-20",
    },
    {
      id: "63",
      title: "Unauthorized Debit Card Transaction",
      content: "Unauthorized transaction made on debit card.",
      category: "Debit Card",
      decision: "Upheld",
      company: "Lloyds Bank",
      date: "2024-03-27",
    },
    {
      id: "64",
      title: "Misreported Credit Information",
      content: "Credit information was misreported to the credit bureau.",
      category: "Credit Report",
      decision: "Partially Upheld",
      company: "Experian Plc",
      date: "2024-04-01",
    },
    {
      id: "65",
      title: "Incorrect Mortgage Rate",
      content: "Incorrect interest rate applied to mortgage account.",
      category: "Mortgage",
      decision: "Upheld",
      company: "Barclays Bank Plc",
      date: "2024-04-10",
    },
    {
      id: "66",
      title: "Lost Cheque",
      content: "Customer's cheque was lost during bank processing.",
      category: "Cheque",
      decision: "Upheld",
      company: "HSBC Holdings",
      date: "2024-04-15",
    },
    {
      id: "67",
      title: "Credit Card Fraud",
      content: "Unauthorized transactions on customer's credit card.",
      category: "Credit Card",
      decision: "Rejected",
      company: "NatWest Bank",
      date: "2024-04-22",
    },
    {
      id: "68",
      title: "Overdraft Charge Dispute",
      content: "Unexpected overdraft charges on the customer's account.",
      category: "Overdraft",
      decision: "Upheld",
      company: "Lloyds Bank",
      date: "2024-04-28",
    },
    {
      id: "69",
      title: "Insurance Coverage Issue",
      content: "Dispute over insurance policy coverage.",
      category: "Insurance",
      decision: "Partially Upheld",
      company: "Aviva Plc",
      date: "2024-05-05",
    },
    {
      id: "70",
      title: "Delayed PPI Refund",
      content: "Payment Protection Insurance (PPI) refund was delayed.",
      category: "PPI",
      decision: "Upheld",
      company: "Barclays Bank Plc",
      date: "2024-05-10",
    },
    {
      id: "71",
      title: "Duplicate Direct Debit",
      content: "Direct debit payment was taken twice for the same bill.",
      category: "Direct Debit",
      decision: "Rejected",
      company: "NatWest Bank",
      date: "2024-05-17",
    },
    {
      id: "72",
      title: "Card Declined at POS",
      content: "Debit card was incorrectly declined at point of sale.",
      category: "Debit Card",
      decision: "Partially Upheld",
      company: "HSBC Holdings",
      date: "2024-05-25",
    },
    {
      id: "73",
      title: "Unauthorized Standing Order Setup",
      content: "Standing order was set up without the customer's authorization.",
      category: "Standing Order",
      decision: "Rejected",
      company: "Santander UK",
      date: "2024-06-02",
    },
    {
      id: "74",
      title: "Misprocessed Loan Payment",
      content: "Loan payment was applied to the wrong account.",
      category: "Loan",
      decision: "Upheld",
      company: "Lloyds Bank",
      date: "2024-06-07",
    },
    {
      id: "75",
      title: "Fraudulent ATM Withdrawal",
      content: "Unauthorized ATM withdrawal made from customer's account.",
      category: "ATM",
      decision: "Rejected",
      company: "Metro Bank",
      date: "2024-06-14",
    },
    {
      id: "76",
      title: "Delayed Funds Transfer",
      content: "Funds transfer between accounts was delayed.",
      category: "Funds Transfer",
      decision: "Upheld",
      company: "Barclays Bank Plc",
      date: "2024-06-20",
    },
    {
      id: "77",
      title: "Overcharged International Transfer Fee",
      content: "Unexpected fees applied to international money transfer.",
      category: "Funds Transfer",
      decision: "Partially Upheld",
      company: "HSBC Holdings",
      date: "2024-06-28",
    },
    {
      id: "78",
      title: "Mortgage Payment Issue",
      content: "Mortgage payment date was changed without prior notice.",
      category: "Mortgage",
      decision: "Rejected",
      company: "Santander UK",
      date: "2024-07-05",
    },
    {
      id: "79",
      title: "Debit Card Fraudulent Transaction",
      content: "Fraudulent transaction occurred using the customer's debit card.",
      category: "Debit Card",
      decision: "Upheld",
      company: "Barclays Bank Plc",
      date: "2024-07-10",
    },
    {
      id: "80",
      title: "Loan Repayment Dispute",
      content: "Discrepancy in loan repayment schedule.",
      category: "Loan",
      decision: "Rejected",
      company: "HSBC Holdings",
      date: "2024-07-18",
    },
    {
      id: "81",
      title: "Savings Account Freeze",
      content: "Savings account was frozen without prior notification.",
      category: "Savings Account",
      decision: "Upheld",
      company: "Nationwide Building Society",
      date: "2024-07-25",
    },
    {
      id: "82",
      title: "ATM Cash Discrepancy",
      content: "Customer was given incorrect amount of cash by ATM.",
      category: "ATM",
      decision: "Rejected",
      company: "Lloyds Bank",
      date: "2024-08-01",
    },
    {
      id: "83",
      title: "Unauthorized Credit Card Charges",
      content: "Unrecognized transactions appeared on the customer's credit card statement.",
      category: "Credit Card",
      decision: "Upheld",
      company: "HSBC Holdings",
      date: "2024-08-08",
    },
    {
      id: "84",
      title: "Incorrect Direct Debit Setup",
      content: "Direct debit was set up for the wrong amount.",
      category: "Direct Debit",
      decision: "Partially Upheld",
      company: "Santander UK",
      date: "2024-08-12",
    },
    {
      id: "85",
      title: "Incorrect Savings Account Interest",
      content: "Incorrect interest was applied to the customer's savings account.",
      category: "Savings Account",
      decision: "Rejected",
      company: "Nationwide Building Society",
      date: "2024-08-19",
    },
    {
      id: "86",
      title: "Cheque Not Cleared",
      content: "Cheque failed to clear despite sufficient funds.",
      category: "Cheque",
      decision: "Upheld",
      company: "Lloyds Bank",
      date: "2024-08-25",
    },
    {
      id: "87",
      title: "Unauthorized Account Closure",
      content: "Bank closed the account without informing the customer.",
      category: "Current Account",
      decision: "Rejected",
      company: "NatWest Bank",
      date: "2024-08-29",
    },
    {
      id: "88",
      title: "PPI Refund Delay",
      content: "PPI refund was delayed beyond the promised time frame.",
      category: "PPI",
      decision: "Upheld",
      company: "Barclays Bank Plc",
      date: "2024-09-04",
    },
    {
      id: "89",
      title: "Overpayment on Mortgage",
      content: "Customer overpaid mortgage, and the refund was delayed.",
      category: "Mortgage",
      decision: "Partially Upheld",
      company: "Santander UK",
      date: "2024-09-12",
    },
    {
      id: "90",
      title: "Debit Card Lost in ATM",
      content: "Customer's debit card was lost during an ATM withdrawal.",
      category: "Debit Card",
      decision: "Upheld",
      company: "HSBC Holdings",
      date: "2024-09-20",
    },
    {
      id: "91",
      title: "Delayed Mortgage Approval",
      content: "Mortgage approval process was delayed without notice.",
      category: "Mortgage",
      decision: "Rejected",
      company: "Nationwide Building Society",
      date: "2024-09-27",
    },
    {
      id: "92",
      title: "Incorrect Credit Card Statement",
      content: "Discrepancy found on the customer's credit card statement.",
      category: "Credit Card",
      decision: "Partially Upheld",
      company: "NatWest Bank",
      date: "2024-10-01",
    },
    {
      id: "93",
      title: "Savings Account Fees Dispute",
      content: "Unexpected fees applied to savings account.",
      category: "Savings Account",
      decision: "Rejected",
      company: "Barclays Bank Plc",
      date: "2024-10-10",
    },
    {
      id: "94",
      title: "Incorrect Loan Payment Amount",
      content: "Loan payment amount was higher than agreed upon.",
      category: "Loan",
      decision: "Upheld",
      company: "Lloyds Bank",
      date: "2024-10-15",
    },
    {
      id: "95",
      title: "Insurance Claim Denied",
      content: "Customer's insurance claim was denied without proper review.",
      category: "Insurance",
      decision: "Rejected",
      company: "Aviva Plc",
      date: "2024-10-22",
    },
    {
      id: "96",
      title: "Unauthorized Standing Order Setup",
      content: "Bank set up a standing order without customer consent.",
      category: "Standing Order",
      decision: "Upheld",
      company: "HSBC Holdings",
      date: "2024-10-27",
    },
    {
      id: "97",
      title: "ATM Dispense Failure",
      content: "ATM did not dispense money but debited the account.",
      category: "ATM",
      decision: "Partially Upheld",
      company: "Santander UK",
      date: "2024-11-03",
    },
    {
      id: "98",
      title: "Credit Limit Reduction Without Notice",
      content: "Bank reduced the credit limit without prior notification.",
      category: "Credit Card",
      decision: "Rejected",
      company: "Nationwide Building Society",
      date: "2024-11-09",
    },
    {
      id: "99",
      title: "Foreign Transaction Fee Dispute",
      content: "Unexpected fees applied to a foreign transaction.",
      category: "Credit Card",
      decision: "Upheld",
      company: "Barclays Bank Plc",
      date: "2024-11-15",
    },
    {
      id: "100",
      title: "Lost Debit Card",
      content: "Customer's debit card was lost, and replacement was delayed.",
      category: "Debit Card",
      decision: "Partially Upheld",
      company: "HSBC Holdings",
      date: "2024-11-20",
    },
  ];
};
